#!/bin/bash

echo "=== 1. Delete cache ==="
rm -f runtime/cache/cache.db
find runtime/cache -type f ! -name '.gitkeep' -delete


echo "=== 2. scan-all ==="
./av scan-all



echo "=== 3. restore-all ==="
./av restore-all



echo "=== 4. scan-all (second) ==="
./av scan-all

echo "=== 5. restore-all ==="
./av restore-all

echo "=== Test finished ==="
